
services:
  ebook_library_fe:
    container_name: ebook_library_fe
    build:
      context: .
      dockerfile:
        Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"

volumes:
  postgres-data:
  redis-data:

networks:
  my-network:
    driver: bridge
